name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1
     
     - name: Write permission for Gradlew
       run: chmod +x ./gradlew
     
     - name: Set Up JDK
       uses: actions/setup-java@v1
       with:
         java-version: 11
       
     - name: Build Project
       run: ./gradlew assemble

  release:
   name: Release Project
   runs-on: ubuntu-latest
   needs: build
   steps:
   - name: Download artifact
     uses: actions/download-artifact@v3
     with:
       name: static-site
   - name: Test artifact download
     run: ls -R
