name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1
     
     - name: shoot yourself
       run: chmod +x ./gradlew
     
     - name: stfu android
       uses: actions/setup-java@v1
       with:
         java-version: 11
       
     - name: bruh
       run: ./gradlew assemble
       
     - name: i hate ci
       run: |
        # Build the launcher
        ./gradlew :app:assembleDebug
        mv app/build/app-debug.apk
       
     - name: wtf
       uses: actions/upload-artifact@v2
       with:
          name: app-debug
          path: out/app-debug.apk
